@startuml
left to right direction
actor Client as client #dodgerblue;line:dodgerblue;line.bold;text:black

package Phone #springgreen;line:darkgreen;line.bold;text:black {
  usecase "Show phones" as showPhones
  usecase "Show phone detail" as showPhone
}

client --> showPhones
client --> showPhone
@enduml
