<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20211019152151 extends AbstractMigration
{
    #[\Override]
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE bilemo_client (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_BEDC5C89F85E0677 ON bilemo_client (username)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE bilemo_phone (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, price INT NOT NULL, color VARCHAR(255) NOT NULL, description TEXT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE bilemo_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, pseudo VARCHAR(255) NOT NULL, birthday_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, client_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_69C6AC2519EB6921 ON bilemo_user (client_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE bilemo_user ADD CONSTRAINT FK_69C6AC2519EB6921 FOREIGN KEY (client_id) REFERENCES bilemo_client (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    #[\Override]
    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE bilemo_user DROP CONSTRAINT FK_69C6AC2519EB6921
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE bilemo_client
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE bilemo_phone
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE bilemo_user
        SQL);
    }
}
