@startuml
autonumber
title       "Client" accessing to /api/users/1
actor       "Client"
participant Api
database    Database

ref over "Client", Api, Database
    /api/login_check
end ref
"Client" -> Api: GET /api/users/1
Api -> Database: get user with id 1 associated to the logged client
alt user found for the logged client
    Database --> Api: return users with id = 1
    "Client" <-- Api: return /api/users/1 with 200 status code
else user not found
    Database -> Api: user not found
    Api -> "Client": return /api/users/1 with 404 status code
end

@enduml
